# Generated by Django 4.0.2 on 2022-02-10 08:01

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('city', models.CharField(choices=[('BAN', 'Bangalore')], default='BAN', max_length=10)),
                ('fest_nos', models.IntegerField()),
                ('image', models.ImageField(default='default.jpg', upload_to='college_pics')),
            ],
            options={
                'db_table': 'college',
            },
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Participated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('event', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Fest',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('fest_type', models.CharField(choices=[('CUL', 'Cultural'), ('TEC', 'Technical'), ('COL', 'College'), ('SPO', 'Sports')], default='COL', max_length=10)),
                ('fest_desc', models.TextField(default='This is a fest')),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(auto_now_add=True)),
                ('event_nos', models.IntegerField()),
                ('image', models.ImageField(default='default.jpg', upload_to='fest_pics')),
                ('clg_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.college')),
                ('org_id', models.ManyToManyField(to='webpage.Organizer')),
            ],
            options={
                'db_table': 'fest',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('event_date', models.DateField(auto_now_add=True)),
                ('event_time', models.TimeField(auto_now_add=True)),
                ('event_desc', models.TextField(default='This is an event')),
                ('entry_fee', models.IntegerField()),
                ('fest_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webpage.fest')),
                ('org_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webpage.organizer')),
            ],
            options={
                'db_table': 'event',
            },
        ),
        migrations.AddConstraint(
            model_name='fest',
            constraint=models.CheckConstraint(check=models.Q(('end_date__gte', django.db.models.expressions.F('start_date'))), name='check_start_date'),
        ),
    ]
