# Generated by Django 4.0.2 on 2022-02-10 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0002_alter_organizer_table_alter_participated_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='fest',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='fest',
            name='start_date',
            field=models.DateField(default='2022-2-1'),
        ),
    ]
