# Generated by Django 4.0.2 on 2022-02-10 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0003_alter_event_event_date_alter_event_event_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateField(default='2022-01-01'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_time',
            field=models.TimeField(default='12:00'),
        ),
        migrations.AlterField(
            model_name='fest',
            name='end_date',
            field=models.DateField(default='2022-02-01'),
        ),
        migrations.AlterField(
            model_name='fest',
            name='start_date',
            field=models.DateField(default='2022-01-01'),
        ),
    ]
